from enums.commands import Command
from enums.geometry import Moved

def template(game_context):
    return {
            "MOVE_FORWARD": f"Einen Schritt nach {Moved.FORWARD.value}",
            "TURN_LEFT": f"Drehe dich nach {Moved.LEFT.value}",
            "MOVE_BACK": f"Einen Schritt nach {Moved.BACK.value}",
            "TURN_RIGHT": f"Drehe dich nach {Moved.RIGHT.value}",
            "OPEN_MAP": "Karte öffnen",
            "NAVIGATION": "Steuerung anzeigen",
            "SHUFFLE_MAP": "Räume mischen",
            "OP1": "Menu Auswahl 1",
            "OP2": "Menu Auswahl 2",
            "OP3": "Menu Auswahl 3",
            "OP4": "Menu Auswahl 4",
            "BACK": "Zurück",
            "FORTH": "Weiter",
            "ACCEPT": "Ja",
            "DENIE": "Nein",
            "EXIT": "Verlassen",
            "OPTION1": "1",
            "OPTION2": "2",
            "OPTION3": "3",
            "OPTION4": "4",
            "navigation_command": f"[yellow]{Command.NAVIGATION.value.upper()}[/]",
            "player_facing": game_context.player.facing.value,
            "player_moved": game_context.player.moved.value,
            "object": getattr(game_context.interaction_context.target_object, "value", ""),
            "interaction_type": getattr(game_context.interaction_context.interaction_type, "value", ""),
            "interaction_result": getattr(game_context.interaction_context.interaction_result, "value", ""),
            "bottom_room": game_context.world.bottom_room.name,
            "front_room": game_context.world.front_room.name,
            "right_room": game_context.world.right_room.name,
            "left_room": game_context.world.left_room.name,
            "top_room": game_context.world.top_room.name,
            "back_room": game_context.world.back_room.name,
        }